name: Deploy Firestore Rules
'on':
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'firestore.rules'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Firestore Rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATTYBOX_C0902 }}
